import React from 'react';
import CategoryPageLayout from '../../../../components/ui/CategoryPageLayout';

const products = [
  {
    icon: '\u{1F4F1}',
    image: 'https://loremflickr.com/300/300/electronics?seed=1',
    name: 'Wireless Earbuds Pro Max',
    store: 'TechZone MN',
    price: '$49.99',
    old: '$89.99',
    off: '-44%',
    rating: '4.8',
    reviews: '1.2k',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F4BB}',
    image: 'https://loremflickr.com/300/300/electronics?seed=2',
    name: 'MacBook Air M3 15"',
    store: 'AppleWorld',
    price: '$1,199.00',
    old: '$1,499.00',
    off: '-20%',
    rating: '4.9',
    reviews: '3.4k',
    badge: 'TOP',
    wishlist: false,
  },
  {
    icon: '\u{1F3A7}',
    image: 'https://loremflickr.com/300/300/electronics?seed=3',
    name: 'Studio Headphones - Deep Bass',
    store: 'AudioPro',
    price: '$79.99',
    old: '$149.99',
    off: '-47%',
    rating: '4.9',
    reviews: '2.3k',
    badge: 'TOP',
    wishlist: false,
  },
  {
    icon: '\u{1F4F7}',
    image: 'https://loremflickr.com/300/300/electronics?seed=4',
    name: 'Mirrorless Camera 4K',
    store: 'SnapGear',
    price: '$649.00',
    old: '$899.00',
    off: '-28%',
    rating: '4.7',
    reviews: '891',
    badge: 'SALE',
    wishlist: true,
  },
  {
    icon: '\u{1F50B}',
    image: 'https://loremflickr.com/300/300/electronics?seed=5',
    name: 'Portable Power Bank 20000mAh',
    store: 'ChargeUp',
    price: '$29.99',
    old: '$49.99',
    off: '-40%',
    rating: '4.6',
    reviews: '1.8k',
    badge: 'HOT',
    wishlist: false,
  },
  {
    icon: '\u{1F4FA}',
    image: 'https://loremflickr.com/300/300/electronics?seed=6',
    name: 'Smart TV 55" 4K OLED',
    store: 'ViewMax',
    price: '$699.00',
    old: '$999.00',
    off: '-30%',
    rating: '4.8',
    reviews: '2.1k',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{2328}',
    image: 'https://loremflickr.com/300/300/electronics?seed=7',
    name: 'Mechanical Gaming Keyboard',
    store: 'GamerEdge',
    price: '$89.99',
    old: '$129.99',
    off: '-31%',
    rating: '4.7',
    reviews: '567',
    badge: 'NEW',
    wishlist: false,
  },
  {
    icon: '\u{1F5A5}',
    image: 'https://loremflickr.com/300/300/electronics?seed=8',
    name: '27" 144Hz Gaming Monitor',
    store: 'DisplayPro',
    price: '$349.00',
    old: '$499.00',
    off: '-30%',
    rating: '4.8',
    reviews: '1.4k',
    badge: 'HOT',
    wishlist: true,
  },
  {
    icon: '\u{1F4F1}',
    image: 'https://loremflickr.com/300/300/electronics?seed=9',
    name: 'Smartphone Case MagSafe',
    store: 'CaseCraft',
    price: '$24.99',
    old: '$39.99',
    off: '-38%',
    rating: '4.5',
    reviews: '723',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F50C}',
    image: 'https://loremflickr.com/300/300/electronics?seed=10',
    name: 'USB-C Hub 8-in-1',
    store: 'ConnectAll',
    price: '$34.99',
    old: '$59.99',
    off: '-42%',
    rating: '4.6',
    reviews: '445',
    badge: 'NEW',
    wishlist: false,
  },
  {
    icon: '\u{1F3AE}',
    image: 'https://loremflickr.com/300/300/electronics?seed=11',
    name: 'Wireless Gaming Controller',
    store: 'GamerEdge',
    price: '$54.99',
    old: '$79.99',
    off: '-31%',
    rating: '4.7',
    reviews: '1.1k',
    badge: 'HOT',
    wishlist: false,
  },
  {
    icon: '\u{1F4BB}',
    image: 'https://loremflickr.com/300/300/electronics?seed=12',
    name: 'Laptop Stand Adjustable',
    store: 'DeskMate',
    price: '$34.99',
    old: '$55.00',
    off: '-36%',
    rating: '4.5',
    reviews: '312',
    badge: 'SALE',
    wishlist: false,
  },
];

const ElectronicsView = () => (
  <CategoryPageLayout
    title="Electronics"
    icon={'\u{1F4F1}'}
    description="Discover the latest gadgets, phones, laptops, and tech accessories."
    products={products}
  />
);

export default ElectronicsView;
