import React from 'react';
import CategoryPageLayout from '../../../../components/ui/CategoryPageLayout';

const products = [
  {
    icon: '\u{1F34E}',
    image: 'https://loremflickr.com/300/300/food?seed=1',
    name: 'Organic Fruit Basket Mix',
    store: 'FreshFarm',
    price: '$24.99',
    old: '$39.99',
    off: '-38%',
    rating: '4.7',
    reviews: '1.1k',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F950}',
    image: 'https://loremflickr.com/300/300/food?seed=2',
    name: 'Artisan Bread Box Set',
    store: 'BakeHouse',
    price: '$18.99',
    old: '$34.99',
    off: '-46%',
    rating: '4.6',
    reviews: '567',
    badge: 'NEW',
    wishlist: false,
  },
  {
    icon: '\u{1F9C0}',
    image: 'https://loremflickr.com/300/300/food?seed=3',
    name: 'Premium Cheese Platter Kit',
    store: 'DairyBest',
    price: '$34.99',
    old: '$54.99',
    off: '-36%',
    rating: '4.8',
    reviews: '432',
    badge: 'HOT',
    wishlist: true,
  },
  {
    icon: '\u{2615}',
    image: 'https://loremflickr.com/300/300/food?seed=4',
    name: 'Single Origin Coffee Beans 1kg',
    store: 'BrewMaster',
    price: '$19.99',
    old: '$32.99',
    off: '-39%',
    rating: '4.9',
    reviews: '2.3k',
    badge: 'TOP',
    wishlist: false,
  },
  {
    icon: '\u{1F36B}',
    image: 'https://loremflickr.com/300/300/food?seed=5',
    name: 'Dark Chocolate Collection 12pc',
    store: 'CocoaCraft',
    price: '$14.99',
    old: '$24.99',
    off: '-40%',
    rating: '4.7',
    reviews: '876',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F954}',
    image: 'https://loremflickr.com/300/300/food?seed=6',
    name: 'Organic Veggie Box Weekly',
    store: 'FreshFarm',
    price: '$29.99',
    old: '$44.99',
    off: '-33%',
    rating: '4.5',
    reviews: '345',
    badge: 'NEW',
    wishlist: false,
  },
  {
    icon: '\u{1F375}',
    image: 'https://loremflickr.com/300/300/food?seed=7',
    name: 'Japanese Green Tea Set',
    store: 'TeaLeaf',
    price: '$22.99',
    old: '$39.99',
    off: '-43%',
    rating: '4.6',
    reviews: '654',
    badge: 'HOT',
    wishlist: false,
  },
  {
    icon: '\u{1F36F}',
    image: 'https://loremflickr.com/300/300/food?seed=8',
    name: 'Raw Manuka Honey 500g',
    store: 'BeeNatural',
    price: '$39.99',
    old: '$64.99',
    off: '-38%',
    rating: '4.8',
    reviews: '912',
    badge: 'TOP',
    wishlist: false,
  },
  {
    icon: '\u{1F951}',
    image: 'https://loremflickr.com/300/300/food?seed=9',
    name: 'Superfood Smoothie Pack 10ct',
    store: 'HealthBlend',
    price: '$27.99',
    old: '$44.99',
    off: '-38%',
    rating: '4.5',
    reviews: '234',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F969}',
    image: 'https://loremflickr.com/300/300/food?seed=10',
    name: 'Premium Wagyu Beef Pack',
    store: 'MeatCraft',
    price: '$89.99',
    old: '$129.99',
    off: '-31%',
    rating: '4.9',
    reviews: '187',
    badge: 'TOP',
    wishlist: true,
  },
  {
    icon: '\u{1F35D}',
    image: 'https://loremflickr.com/300/300/food?seed=11',
    name: 'Italian Pasta Collection 6pk',
    store: 'PastaWorks',
    price: '$16.99',
    old: '$27.99',
    off: '-39%',
    rating: '4.4',
    reviews: '456',
    badge: 'NEW',
    wishlist: false,
  },
  {
    icon: '\u{1F96C}',
    image: 'https://loremflickr.com/300/300/food?seed=12',
    name: 'Organic Spice Rack Set 12',
    store: 'SpiceTrail',
    price: '$32.99',
    old: '$54.99',
    off: '-40%',
    rating: '4.6',
    reviews: '567',
    badge: 'SALE',
    wishlist: false,
  },
];

const FoodGrocerySection = () => (
  <CategoryPageLayout
    title="Food & Grocery"
    icon={'\u{1F34E}'}
    description="Fresh produce, gourmet foods, pantry staples, and specialty ingredients."
    products={products}
  />
);

export default FoodGrocerySection;
