import React from 'react';
import CategoryPageLayout from '../../../../components/ui/CategoryPageLayout';

const products = [
  {
    icon: '\u{1F436}',
    image: 'https://loremflickr.com/300/300/pets?seed=1',
    name: 'Premium Dog Food 15lb Bag',
    store: 'PawsFirst',
    price: '$34.99',
    old: '$54.99',
    off: '-36%',
    rating: '4.8',
    reviews: '2.3k',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F431}',
    image: 'https://loremflickr.com/300/300/pets?seed=2',
    name: 'Cat Tree Tower 5-Level',
    store: 'MeowHaven',
    price: '$69.99',
    old: '$119.99',
    off: '-42%',
    rating: '4.7',
    reviews: '1.1k',
    badge: 'HOT',
    wishlist: true,
  },
  {
    icon: '\u{1F9B4}',
    image: 'https://loremflickr.com/300/300/pets?seed=3',
    name: 'Indestructible Dog Chew Toy',
    store: 'ToughPup',
    price: '$12.99',
    old: '$22.99',
    off: '-43%',
    rating: '4.5',
    reviews: '876',
    badge: 'NEW',
    wishlist: false,
  },
  {
    icon: '\u{1F41F}',
    image: 'https://loremflickr.com/300/300/pets?seed=4',
    name: 'Aquarium Starter Kit 20gal',
    store: 'AquaLife',
    price: '$89.99',
    old: '$149.99',
    off: '-40%',
    rating: '4.6',
    reviews: '345',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F43E}',
    image: 'https://loremflickr.com/300/300/pets?seed=5',
    name: 'Pet Grooming Kit 8-in-1',
    store: 'PetSpa',
    price: '$29.99',
    old: '$49.99',
    off: '-40%',
    rating: '4.7',
    reviews: '567',
    badge: 'TOP',
    wishlist: false,
  },
  {
    icon: '\u{1F436}',
    image: 'https://loremflickr.com/300/300/pets?seed=6',
    name: 'Orthopedic Dog Bed Large',
    store: 'PawsFirst',
    price: '$44.99',
    old: '$79.99',
    off: '-44%',
    rating: '4.8',
    reviews: '654',
    badge: 'HOT',
    wishlist: false,
  },
  {
    icon: '\u{1F426}',
    image: 'https://loremflickr.com/300/300/pets?seed=7',
    name: 'Bird Cage Deluxe with Stand',
    store: 'WingHome',
    price: '$59.99',
    old: '$99.99',
    off: '-40%',
    rating: '4.4',
    reviews: '234',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F431}',
    image: 'https://loremflickr.com/300/300/pets?seed=8',
    name: 'Automated Cat Feeder Smart',
    store: 'TechPet',
    price: '$49.99',
    old: '$84.99',
    off: '-41%',
    rating: '4.6',
    reviews: '432',
    badge: 'NEW',
    wishlist: false,
  },
  {
    icon: '\u{1F43E}',
    image: 'https://loremflickr.com/300/300/pets?seed=9',
    name: 'Pet Carrier Airline Approved',
    store: 'TravelPet',
    price: '$39.99',
    old: '$64.99',
    off: '-38%',
    rating: '4.5',
    reviews: '345',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F436}',
    image: 'https://loremflickr.com/300/300/pets?seed=10',
    name: 'Dog Harness No-Pull Padded',
    store: 'WalkMate',
    price: '$24.99',
    old: '$39.99',
    off: '-38%',
    rating: '4.7',
    reviews: '1.2k',
    badge: 'HOT',
    wishlist: false,
  },
  {
    icon: '\u{1F422}',
    image: 'https://loremflickr.com/300/300/pets?seed=11',
    name: 'Reptile Terrarium Kit Complete',
    store: 'ExoticPets',
    price: '$79.99',
    old: '$129.99',
    off: '-38%',
    rating: '4.3',
    reviews: '187',
    badge: 'NEW',
    wishlist: false,
  },
  {
    icon: '\u{1F431}',
    image: 'https://loremflickr.com/300/300/pets?seed=12',
    name: 'Interactive Cat Laser Toy',
    store: 'PlayPaws',
    price: '$14.99',
    old: '$24.99',
    off: '-40%',
    rating: '4.6',
    reviews: '789',
    badge: 'SALE',
    wishlist: true,
  },
];

const PetSuppliesSection = () => (
  <CategoryPageLayout
    title="Pet Supplies"
    icon={'\u{1F43E}'}
    description="Food, toys, accessories, and care essentials for dogs, cats, and all pets."
    products={products}
  />
);

export default PetSuppliesSection;
