import React from 'react';
import CategoryPageLayout from '../../../../components/ui/CategoryPageLayout';

const products = [
  {
    icon: '\u{1F484}',
    image: 'https://loremflickr.com/300/300/beauty?seed=1',
    name: 'Matte Lipstick Collection 6pk',
    store: 'GlowUp',
    price: '$24.99',
    old: '$44.99',
    off: '-44%',
    rating: '4.8',
    reviews: '2.1k',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F9F4}',
    image: 'https://loremflickr.com/300/300/beauty?seed=2',
    name: 'Hyaluronic Acid Serum 30ml',
    store: 'SkinScience',
    price: '$19.99',
    old: '$39.99',
    off: '-50%',
    rating: '4.9',
    reviews: '3.4k',
    badge: 'TOP',
    wishlist: true,
  },
  {
    icon: '\u{1F489}',
    image: 'https://loremflickr.com/300/300/beauty?seed=3',
    name: 'Retinol Night Cream',
    store: 'DermaGlow',
    price: '$34.99',
    old: '$59.99',
    off: '-42%',
    rating: '4.7',
    reviews: '1.2k',
    badge: 'HOT',
    wishlist: false,
  },
  {
    icon: '\u{1F338}',
    image: 'https://loremflickr.com/300/300/beauty?seed=4',
    name: 'Rose Petal Face Mist',
    store: 'FloralBeauty',
    price: '$14.99',
    old: '$24.99',
    off: '-40%',
    rating: '4.5',
    reviews: '567',
    badge: 'NEW',
    wishlist: false,
  },
  {
    icon: '\u{1F485}',
    image: 'https://loremflickr.com/300/300/beauty?seed=5',
    name: 'Gel Nail Kit Professional',
    store: 'NailArt',
    price: '$29.99',
    old: '$54.99',
    off: '-45%',
    rating: '4.6',
    reviews: '789',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F9F4}',
    image: 'https://loremflickr.com/300/300/beauty?seed=6',
    name: 'Vitamin C Brightening Set',
    store: 'SkinScience',
    price: '$44.99',
    old: '$79.99',
    off: '-44%',
    rating: '4.8',
    reviews: '1.8k',
    badge: 'TOP',
    wishlist: false,
  },
  {
    icon: '\u{1F48E}',
    image: 'https://loremflickr.com/300/300/beauty?seed=7',
    name: 'Crystal Facial Roller Jade',
    store: 'ZenBeauty',
    price: '$12.99',
    old: '$24.99',
    off: '-48%',
    rating: '4.4',
    reviews: '456',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{2728}',
    image: 'https://loremflickr.com/300/300/beauty?seed=8',
    name: 'Highlighter Palette Shimmer',
    store: 'GlowUp',
    price: '$18.99',
    old: '$34.99',
    off: '-46%',
    rating: '4.6',
    reviews: '923',
    badge: 'HOT',
    wishlist: true,
  },
  {
    icon: '\u{1F338}',
    image: 'https://loremflickr.com/300/300/beauty?seed=9',
    name: 'Organic Hair Oil Argan',
    store: 'HairBliss',
    price: '$16.99',
    old: '$29.99',
    off: '-43%',
    rating: '4.7',
    reviews: '678',
    badge: 'NEW',
    wishlist: false,
  },
  {
    icon: '\u{1F9FC}',
    image: 'https://loremflickr.com/300/300/beauty?seed=10',
    name: 'Charcoal Detox Face Wash',
    store: 'CleanSkin',
    price: '$11.99',
    old: '$21.99',
    off: '-45%',
    rating: '4.5',
    reviews: '345',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F484}',
    image: 'https://loremflickr.com/300/300/beauty?seed=11',
    name: 'Eyeshadow Palette 18 Colors',
    store: 'ColorPop',
    price: '$22.99',
    old: '$39.99',
    off: '-43%',
    rating: '4.7',
    reviews: '1.4k',
    badge: 'HOT',
    wishlist: false,
  },
  {
    icon: '\u{1F338}',
    image: 'https://loremflickr.com/300/300/beauty?seed=12',
    name: 'Lavender Bath Bomb Set 6pk',
    store: 'SpaLux',
    price: '$17.99',
    old: '$29.99',
    off: '-40%',
    rating: '4.4',
    reviews: '234',
    badge: 'NEW',
    wishlist: false,
  },
];

const BeautySection = () => (
  <CategoryPageLayout
    title="Beauty"
    icon={'\u{1F484}'}
    description="Skincare, makeup, haircare, and wellness products from top brands."
    products={products}
  />
);

export default BeautySection;
