import React from 'react';
import CategoryPageLayout from '../../../../components/ui/CategoryPageLayout';

const products = [
  {
    icon: '\u{1F457}',
    image: 'https://loremflickr.com/300/300/fashion?seed=1',
    name: 'Silk Evening Dress',
    store: 'GlamourFit',
    price: '$89.99',
    old: '$159.99',
    off: '-44%',
    rating: '4.8',
    reviews: '1.5k',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F45F}',
    image: 'https://loremflickr.com/300/300/fashion?seed=2',
    name: 'Urban Runner Sneakers',
    store: 'SoleStyle',
    price: '$64.99',
    old: '$110.00',
    off: '-41%',
    rating: '4.6',
    reviews: '847',
    badge: 'HOT',
    wishlist: true,
  },
  {
    icon: '\u{1F454}',
    image: 'https://loremflickr.com/300/300/fashion?seed=3',
    name: 'Slim Fit Business Shirt',
    store: 'ProWear',
    price: '$39.99',
    old: '$69.99',
    off: '-43%',
    rating: '4.5',
    reviews: '634',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F45C}',
    image: 'https://loremflickr.com/300/300/fashion?seed=4',
    name: 'Leather Crossbody Bag',
    store: 'LuxeCarry',
    price: '$54.99',
    old: '$95.00',
    off: '-42%',
    rating: '4.7',
    reviews: '433',
    badge: 'HOT',
    wishlist: true,
  },
  {
    icon: '\u{1F576}',
    image: 'https://loremflickr.com/300/300/fashion?seed=5',
    name: 'Premium Polarized Sunglasses',
    store: 'VisionX',
    price: '$28.99',
    old: '$59.99',
    off: '-52%',
    rating: '4.7',
    reviews: '523',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F9E3}',
    image: 'https://loremflickr.com/300/300/fashion?seed=6',
    name: 'Cashmere Winter Scarf',
    store: 'CozyKnit',
    price: '$34.99',
    old: '$65.00',
    off: '-46%',
    rating: '4.6',
    reviews: '289',
    badge: 'NEW',
    wishlist: false,
  },
  {
    icon: '\u{1F45E}',
    image: 'https://loremflickr.com/300/300/fashion?seed=7',
    name: 'Classic Leather Boots',
    store: 'BootCraft',
    price: '$119.00',
    old: '$189.00',
    off: '-37%',
    rating: '4.8',
    reviews: '912',
    badge: 'TOP',
    wishlist: false,
  },
  {
    icon: '\u{1F392}',
    image: 'https://loremflickr.com/300/300/fashion?seed=8',
    name: 'Canvas Travel Backpack',
    store: 'PackLight',
    price: '$44.99',
    old: '$79.99',
    off: '-44%',
    rating: '4.5',
    reviews: '567',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F458}',
    image: 'https://loremflickr.com/300/300/fashion?seed=9',
    name: 'Floral Summer Blouse',
    store: 'BloomStyle',
    price: '$29.99',
    old: '$49.99',
    off: '-40%',
    rating: '4.4',
    reviews: '345',
    badge: 'NEW',
    wishlist: false,
  },
  {
    icon: '\u{1F9E4}',
    image: 'https://loremflickr.com/300/300/fashion?seed=10',
    name: 'Merino Wool Gloves',
    store: 'WinterGear',
    price: '$19.99',
    old: '$35.00',
    off: '-43%',
    rating: '4.3',
    reviews: '198',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F455}',
    image: 'https://loremflickr.com/300/300/fashion?seed=11',
    name: 'Graphic Print T-Shirt',
    store: 'StreetWave',
    price: '$24.99',
    old: '$39.99',
    off: '-38%',
    rating: '4.5',
    reviews: '1.1k',
    badge: 'HOT',
    wishlist: false,
  },
  {
    icon: '\u{1FA73}',
    image: 'https://loremflickr.com/300/300/fashion?seed=12',
    name: 'High-Waist Denim Jeans',
    store: 'DenimCo',
    price: '$49.99',
    old: '$85.00',
    off: '-41%',
    rating: '4.6',
    reviews: '756',
    badge: 'SALE',
    wishlist: false,
  },
];

const FashionSection = () => (
  <CategoryPageLayout
    title="Fashion"
    icon={'\u{1F457}'}
    description="Trending styles, premium clothing, shoes, and accessories for every occasion."
    products={products}
  />
);

export default FashionSection;
