import React from 'react';
import CategoryPageLayout from '../../../../components/ui/CategoryPageLayout';

const products = [
  {
    icon: '\u{1F9F8}',
    image: 'https://loremflickr.com/300/300/toys?seed=1',
    name: 'LEGO Star Wars Millennium Falcon',
    store: 'BrickWorld',
    price: '$79.99',
    old: '$129.99',
    off: '-38%',
    rating: '4.9',
    reviews: '3.4k',
    badge: 'TOP',
    wishlist: true,
  },
  {
    icon: '\u{1F3A8}',
    image: 'https://loremflickr.com/300/300/toys?seed=2',
    name: 'Kids Art Supply Set 150pc',
    store: 'CreativeKids',
    price: '$29.99',
    old: '$49.99',
    off: '-40%',
    rating: '4.7',
    reviews: '1.2k',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F9E9}',
    image: 'https://loremflickr.com/300/300/toys?seed=3',
    name: 'Wooden Puzzle Set 6-in-1',
    store: 'SmartPlay',
    price: '$24.99',
    old: '$44.99',
    off: '-44%',
    rating: '4.6',
    reviews: '567',
    badge: 'HOT',
    wishlist: false,
  },
  {
    icon: '\u{1F680}',
    image: 'https://loremflickr.com/300/300/toys?seed=4',
    name: 'Remote Control Space Shuttle',
    store: 'ToyGalaxy',
    price: '$44.99',
    old: '$74.99',
    off: '-40%',
    rating: '4.5',
    reviews: '345',
    badge: 'NEW',
    wishlist: false,
  },
  {
    icon: '\u{1F3B9}',
    image: 'https://loremflickr.com/300/300/toys?seed=5',
    name: 'Kids Piano Mat Musical',
    store: 'MusicFun',
    price: '$19.99',
    old: '$34.99',
    off: '-43%',
    rating: '4.4',
    reviews: '234',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F4A7}',
    image: 'https://loremflickr.com/300/300/toys?seed=6',
    name: 'Water Gun Super Soaker Set',
    store: 'SummerFun',
    price: '$16.99',
    old: '$29.99',
    off: '-43%',
    rating: '4.6',
    reviews: '876',
    badge: 'HOT',
    wishlist: false,
  },
  {
    icon: '\u{1F52C}',
    image: 'https://loremflickr.com/300/300/toys?seed=7',
    name: 'Kids Science Experiment Kit',
    store: 'SmartPlay',
    price: '$34.99',
    old: '$59.99',
    off: '-42%',
    rating: '4.8',
    reviews: '654',
    badge: 'TOP',
    wishlist: false,
  },
  {
    icon: '\u{1F999}',
    image: 'https://loremflickr.com/300/300/toys?seed=8',
    name: 'Giant Stuffed Llama 3ft',
    store: 'CuddlePals',
    price: '$29.99',
    old: '$49.99',
    off: '-40%',
    rating: '4.7',
    reviews: '432',
    badge: 'SALE',
    wishlist: true,
  },
  {
    icon: '\u{1F9E9}',
    image: 'https://loremflickr.com/300/300/toys?seed=9',
    name: 'Magnetic Building Blocks 100pc',
    store: 'BuildGenius',
    price: '$39.99',
    old: '$69.99',
    off: '-43%',
    rating: '4.8',
    reviews: '1.5k',
    badge: 'HOT',
    wishlist: false,
  },
  {
    icon: '\u{1F3A2}',
    image: 'https://loremflickr.com/300/300/toys?seed=10',
    name: 'Racing Track Set Electric',
    store: 'SpeedRacer',
    price: '$54.99',
    old: '$89.99',
    off: '-39%',
    rating: '4.5',
    reviews: '287',
    badge: 'NEW',
    wishlist: false,
  },
  {
    icon: '\u{1F3AD}',
    image: 'https://loremflickr.com/300/300/toys?seed=11',
    name: 'Puppet Theater Playset',
    store: 'ImaginePlay',
    price: '$39.99',
    old: '$64.99',
    off: '-38%',
    rating: '4.4',
    reviews: '198',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F916}',
    image: 'https://loremflickr.com/300/300/toys?seed=12',
    name: 'Coding Robot Kit for Kids',
    store: 'TechKids',
    price: '$59.99',
    old: '$99.99',
    off: '-40%',
    rating: '4.7',
    reviews: '567',
    badge: 'TOP',
    wishlist: false,
  },
];

const ToysKidsSection = () => (
  <CategoryPageLayout
    title="Toys & Kids"
    icon={'\u{1F9F8}'}
    description="Educational toys, games, outdoor fun, and creative kits for all ages."
    products={products}
  />
);

export default ToysKidsSection;
