import React from 'react';
import CategoryPageLayout from '../../../../components/ui/CategoryPageLayout';

const products = [
  {
    icon: '\u{1F6CB}',
    image: 'https://loremflickr.com/300/300/furniture?seed=1',
    name: 'Modern Sectional Sofa L-Shape',
    store: 'ComfortLiving',
    price: '$799.00',
    old: '$1,299.00',
    off: '-38%',
    rating: '4.8',
    reviews: '1.2k',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F33F}',
    image: 'https://loremflickr.com/300/300/furniture?seed=2',
    name: 'Indoor Plant Collection 3-Pack',
    store: 'GreenHome',
    price: '$39.99',
    old: '$65.00',
    off: '-38%',
    rating: '4.6',
    reviews: '218',
    badge: 'NEW',
    wishlist: false,
  },
  {
    icon: '\u{1F6BF}',
    image: 'https://loremflickr.com/300/300/furniture?seed=3',
    name: 'Rain Shower Head Stainless',
    store: 'BathLux',
    price: '$54.99',
    old: '$89.99',
    off: '-39%',
    rating: '4.7',
    reviews: '456',
    badge: 'HOT',
    wishlist: false,
  },
  {
    icon: '\u{1F56F}',
    image: 'https://loremflickr.com/300/300/furniture?seed=4',
    name: 'Scented Soy Candle Set 4pk',
    store: 'AromaHome',
    price: '$24.99',
    old: '$44.99',
    off: '-44%',
    rating: '4.5',
    reviews: '789',
    badge: 'SALE',
    wishlist: true,
  },
  {
    icon: '\u{1FA91}',
    image: 'https://loremflickr.com/300/300/furniture?seed=5',
    name: 'Ergonomic Office Chair',
    store: 'DeskMate',
    price: '$249.00',
    old: '$399.00',
    off: '-38%',
    rating: '4.8',
    reviews: '1.5k',
    badge: 'TOP',
    wishlist: false,
  },
  {
    icon: '\u{1F3A8}',
    image: 'https://loremflickr.com/300/300/furniture?seed=6',
    name: 'Abstract Wall Art Canvas',
    store: 'ArtVibe',
    price: '$34.99',
    old: '$59.99',
    off: '-42%',
    rating: '4.4',
    reviews: '312',
    badge: 'NEW',
    wishlist: false,
  },
  {
    icon: '\u{1F373}',
    image: 'https://loremflickr.com/300/300/furniture?seed=7',
    name: 'Non-Stick Cookware Set 5pc',
    store: 'HomeChef',
    price: '$89.00',
    old: '$149.00',
    off: '-40%',
    rating: '4.8',
    reviews: '654',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F343}',
    image: 'https://loremflickr.com/300/300/furniture?seed=8',
    name: 'Garden Tool Set 12-Piece',
    store: 'GreenThumb',
    price: '$44.99',
    old: '$74.99',
    off: '-40%',
    rating: '4.6',
    reviews: '387',
    badge: 'HOT',
    wishlist: false,
  },
  {
    icon: '\u{1F4A1}',
    image: 'https://loremflickr.com/300/300/furniture?seed=9',
    name: 'Smart LED Light Strip 5m',
    store: 'BrightLife',
    price: '$19.99',
    old: '$34.99',
    off: '-43%',
    rating: '4.5',
    reviews: '923',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F6CF}',
    image: 'https://loremflickr.com/300/300/furniture?seed=10',
    name: 'Memory Foam Pillow Set',
    store: 'SleepWell',
    price: '$39.99',
    old: '$69.99',
    off: '-43%',
    rating: '4.7',
    reviews: '1.1k',
    badge: 'TOP',
    wishlist: false,
  },
  {
    icon: '\u{1FA9F}',
    image: 'https://loremflickr.com/300/300/furniture?seed=11',
    name: 'Ceramic Planter Set 3pk',
    store: 'GreenHome',
    price: '$29.99',
    old: '$49.99',
    off: '-40%',
    rating: '4.3',
    reviews: '234',
    badge: 'NEW',
    wishlist: false,
  },
  {
    icon: '\u{1F9F9}',
    image: 'https://loremflickr.com/300/300/furniture?seed=12',
    name: 'Robot Vacuum Smart Cleaner',
    store: 'CleanTech',
    price: '$199.00',
    old: '$349.00',
    off: '-43%',
    rating: '4.7',
    reviews: '876',
    badge: 'HOT',
    wishlist: true,
  },
];

const HomeGardenSection = () => (
  <CategoryPageLayout
    title="Home & Garden"
    icon={'\u{1F3E1}'}
    description="Everything for your home — furniture, décor, kitchen, bath, and garden essentials."
    products={products}
  />
);

export default HomeGardenSection;
