import React from 'react';
import CategoryPageLayout from '../../../../components/ui/CategoryPageLayout';

const products = [
  {
    icon: '\u{1F4DA}',
    image: 'https://loremflickr.com/300/300/books?seed=1',
    name: 'Atomic Habits - James Clear',
    store: 'BookNest',
    price: '$11.99',
    old: '$24.99',
    off: '-52%',
    rating: '4.9',
    reviews: '12.4k',
    badge: 'TOP',
    wishlist: true,
  },
  {
    icon: '\u{1F4D6}',
    image: 'https://loremflickr.com/300/300/books?seed=2',
    name: 'The Psychology of Money',
    store: 'ReadMore',
    price: '$13.99',
    old: '$22.99',
    off: '-39%',
    rating: '4.8',
    reviews: '8.7k',
    badge: 'HOT',
    wishlist: false,
  },
  {
    icon: '\u{1F4D5}',
    image: 'https://loremflickr.com/300/300/books?seed=3',
    name: 'Dune - Frank Herbert',
    store: 'SciFiBooks',
    price: '$9.99',
    old: '$18.99',
    off: '-47%',
    rating: '4.7',
    reviews: '5.6k',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F4D8}',
    image: 'https://loremflickr.com/300/300/books?seed=4',
    name: 'Clean Code - Robert Martin',
    store: 'TechBooks',
    price: '$29.99',
    old: '$49.99',
    off: '-40%',
    rating: '4.8',
    reviews: '3.2k',
    badge: 'TOP',
    wishlist: false,
  },
  {
    icon: '\u{1F4D3}',
    image: 'https://loremflickr.com/300/300/books?seed=5',
    name: 'Bullet Journal Dotted 200pg',
    store: 'WriteWell',
    price: '$14.99',
    old: '$24.99',
    off: '-40%',
    rating: '4.6',
    reviews: '1.8k',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F4DA}',
    image: 'https://loremflickr.com/300/300/books?seed=6',
    name: 'Harry Potter Box Set 7 Books',
    store: 'WizardReads',
    price: '$49.99',
    old: '$89.99',
    off: '-44%',
    rating: '4.9',
    reviews: '15.2k',
    badge: 'HOT',
    wishlist: true,
  },
  {
    icon: '\u{1F4D7}',
    image: 'https://loremflickr.com/300/300/books?seed=7',
    name: 'Sapiens - Yuval Harari',
    store: 'HistoryHub',
    price: '$12.99',
    old: '$21.99',
    off: '-41%',
    rating: '4.7',
    reviews: '9.1k',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F4D9}',
    image: 'https://loremflickr.com/300/300/books?seed=8',
    name: 'The Lean Startup',
    store: 'BizBooks',
    price: '$15.99',
    old: '$27.99',
    off: '-43%',
    rating: '4.6',
    reviews: '4.5k',
    badge: 'NEW',
    wishlist: false,
  },
  {
    icon: '\u{1F4D4}',
    image: 'https://loremflickr.com/300/300/books?seed=9',
    name: 'Moleskin Classic Notebook',
    store: 'WriteWell',
    price: '$17.99',
    old: '$29.99',
    off: '-40%',
    rating: '4.5',
    reviews: '2.3k',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F4DA}',
    image: 'https://loremflickr.com/300/300/books?seed=10',
    name: 'Lord of the Rings Trilogy',
    store: 'FantasyReads',
    price: '$34.99',
    old: '$59.99',
    off: '-42%',
    rating: '4.9',
    reviews: '11.7k',
    badge: 'TOP',
    wishlist: false,
  },
  {
    icon: '\u{1F4D6}',
    image: 'https://loremflickr.com/300/300/books?seed=11',
    name: 'Thinking Fast and Slow',
    store: 'MindBooks',
    price: '$14.99',
    old: '$24.99',
    off: '-40%',
    rating: '4.7',
    reviews: '6.8k',
    badge: 'HOT',
    wishlist: false,
  },
  {
    icon: '\u{1F4D5}',
    image: 'https://loremflickr.com/300/300/books?seed=12',
    name: 'Project Hail Mary',
    store: 'SciFiBooks',
    price: '$11.99',
    old: '$19.99',
    off: '-40%',
    rating: '4.8',
    reviews: '4.2k',
    badge: 'NEW',
    wishlist: false,
  },
];

const BooksSection = () => (
  <CategoryPageLayout
    title="Books"
    icon={'\u{1F4DA}'}
    description="Bestsellers, new releases, fiction, non-fiction, and stationery."
    products={products}
  />
);

export default BooksSection;
