import React from 'react';
import CategoryPageLayout from '../../../../components/ui/CategoryPageLayout';

const products = [
  {
    icon: '\u{1F3C0}',
    image: 'https://loremflickr.com/300/300/sports?seed=1',
    name: 'Indoor/Outdoor Basketball',
    store: 'CourtKing',
    price: '$29.99',
    old: '$49.99',
    off: '-40%',
    rating: '4.7',
    reviews: '1.2k',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F3CB}',
    image: 'https://loremflickr.com/300/300/sports?seed=2',
    name: 'Adjustable Dumbbell Set 50lb',
    store: 'FitGear',
    price: '$149.00',
    old: '$249.00',
    off: '-40%',
    rating: '4.9',
    reviews: '2.1k',
    badge: 'TOP',
    wishlist: true,
  },
  {
    icon: '\u{1F6B4}',
    image: 'https://loremflickr.com/300/300/sports?seed=3',
    name: 'Mountain Bike 21-Speed',
    store: 'TrailRider',
    price: '$399.00',
    old: '$649.00',
    off: '-39%',
    rating: '4.8',
    reviews: '567',
    badge: 'HOT',
    wishlist: false,
  },
  {
    icon: '\u{1F3BE}',
    image: 'https://loremflickr.com/300/300/sports?seed=4',
    name: 'Pro Tennis Racket Carbon',
    store: 'AceSport',
    price: '$89.99',
    old: '$149.99',
    off: '-40%',
    rating: '4.6',
    reviews: '345',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{26BD}',
    image: 'https://loremflickr.com/300/300/sports?seed=5',
    name: 'FIFA Match Soccer Ball',
    store: 'GoalZone',
    price: '$34.99',
    old: '$59.99',
    off: '-42%',
    rating: '4.7',
    reviews: '876',
    badge: 'HOT',
    wishlist: false,
  },
  {
    icon: '\u{1F9D8}',
    image: 'https://loremflickr.com/300/300/sports?seed=6',
    name: 'Premium Yoga Mat 6mm',
    store: 'ZenFit',
    price: '$24.99',
    old: '$44.99',
    off: '-44%',
    rating: '4.8',
    reviews: '1.5k',
    badge: 'TOP',
    wishlist: false,
  },
  {
    icon: '\u{1F3CA}',
    image: 'https://loremflickr.com/300/300/sports?seed=7',
    name: 'Competition Swim Goggles',
    store: 'AquaPro',
    price: '$19.99',
    old: '$34.99',
    off: '-43%',
    rating: '4.5',
    reviews: '432',
    badge: 'NEW',
    wishlist: false,
  },
  {
    icon: '\u{1F94A}',
    image: 'https://loremflickr.com/300/300/sports?seed=8',
    name: 'Boxing Gloves Pro 12oz',
    store: 'FightGear',
    price: '$44.99',
    old: '$79.99',
    off: '-44%',
    rating: '4.6',
    reviews: '234',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{26F3}',
    image: 'https://loremflickr.com/300/300/sports?seed=9',
    name: 'Golf Club Set Complete',
    store: 'FairwayPro',
    price: '$299.00',
    old: '$499.00',
    off: '-40%',
    rating: '4.7',
    reviews: '187',
    badge: 'SALE',
    wishlist: true,
  },
  {
    icon: '\u{1F3C3}',
    image: 'https://loremflickr.com/300/300/sports?seed=10',
    name: 'Running Shoes Ultra Boost',
    store: 'PaceSetter',
    price: '$79.99',
    old: '$129.99',
    off: '-38%',
    rating: '4.8',
    reviews: '1.8k',
    badge: 'HOT',
    wishlist: false,
  },
  {
    icon: '\u{1F3D3}',
    image: 'https://loremflickr.com/300/300/sports?seed=11',
    name: 'Table Tennis Set Pro',
    store: 'PingPong+',
    price: '$34.99',
    old: '$59.99',
    off: '-42%',
    rating: '4.4',
    reviews: '345',
    badge: 'NEW',
    wishlist: false,
  },
  {
    icon: '\u{1F3BF}',
    image: 'https://loremflickr.com/300/300/sports?seed=12',
    name: 'Ski Jacket Waterproof',
    store: 'AlpineGear',
    price: '$129.00',
    old: '$219.00',
    off: '-41%',
    rating: '4.7',
    reviews: '456',
    badge: 'SALE',
    wishlist: false,
  },
];

const SportsSection = () => (
  <CategoryPageLayout
    title="Sports"
    icon={'\u{1F3C0}'}
    description="Sports equipment, fitness gear, outdoor adventures, and athletic wear."
    products={products}
  />
);

export default SportsSection;
