import React, { useState, useEffect, useRef } from 'react';
import { Send, Bot, Sparkles, Image as ImageIcon } from 'lucide-react';
import UserMessage from './components/UserMessage';
import AIMessage from './components/AIMessage';

const initialMessages = [
  {
    id: 1,
    type: 'ai',
    content:
      "Hello! I'm your AI assistant. How can I help you today? You can ask me anything from coding help to creative writing.",
    timestamp: '10:00 AM',
    model: 'GPT-4',
    thinking: false,
  },
  {
    id: 2,
    type: 'user',
    content: 'Can you explain React hooks with examples?',
    timestamp: '10:02 AM',
    files: [],
  },
  {
    id: 3,
    type: 'ai',
    content: `React Hooks are functions that let you use state and other React features in functional components.

**Common Hooks:**

1. **useState** - State management
\`\`\`jsx
const [count, setCount] = useState(0);
\`\`\`

2. **useEffect** - Side effects
\`\`\`jsx
useEffect(() => {
  document.title = \`Count: \${count}\`;
}, [count]);
\`\`\`

3. **useContext** - Context API
4. **useRef** - References to DOM elements

Would you like more detailed examples of any specific hook?`,
    timestamp: '10:03 AM',
    model: 'GPT-4',
    thinking: false,
  },
  {
    id: 4,
    type: 'user',
    content: 'Show me a complete example with useEffect',
    timestamp: '10:04 AM',
    files: [],
  },
  {
    id: 5,
    type: 'ai',
    content: `Here's a complete example using \`useEffect\` for data fetching:

\`\`\`jsx
import React, { useState, useEffect } from 'react';

function UserProfile({ userId }) {
  const [user, setUser] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    // This effect runs when userId changes
    const fetchUserData = async () => {
      try {
        setLoading(true);
        const response = await fetch(\`https://api.example.com/users/\${userId}\`);
        const data = await response.json();
        setUser(data);
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };

    fetchUserData();

    // Cleanup function (optional)
    return () => {
      // Cancel any pending requests or cleanup
      console.log('Cleanup for user:', userId);
    };
  }, [userId]); // Dependency array - effect re-runs when userId changes

  if (loading) return <div>Loading...</div>;
  if (error) return <div>Error: {error}</div>;

  return (
    <div>
      <h2>{user.name}</h2>
      <p>Email: {user.email}</p>
    </div>
  );
}
\`\`\`

**Key points:**
- The effect runs after the component mounts
- Re-runs when \`userId\` changes
- Cleanup function prevents memory leaks
- Proper error handling included

This pattern is essential for handling side effects in React components.`,
    timestamp: '10:05 AM',
    model: 'GPT-4',
    thinking: false,
  },
];

const suggestedPrompts = [
  'Write a Python function to sort a list',
  'Explain quantum computing simply',
  'Create a meal plan for weight loss',
  'Design a database schema for e-commerce',
  'Write a poem about technology',
  'Debug this JavaScript code',
  'Plan a 7-day Europe trip itinerary',
  'Explain blockchain technology',
];

// Main Component
const AIChatView = () => {
  const [input, setInput] = useState('');
  const [messages, setMessages] = useState(initialMessages);
  const [isThinking, setIsThinking] = useState(false);
  const messagesEndRef = useRef(null);
  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSend = async (e) => {
    e.preventDefault();
    if (!input.trim() || isThinking) return;

    const userMessage = {
      id: messages.length + 1,
      type: 'user',
      content: input,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      files: [],
    };

    setMessages((prev) => [...prev, userMessage]);
    setInput('');
    setIsThinking(true);

    // Simulate AI thinking
    setTimeout(() => {
      const aiResponse = {
        id: messages.length + 2,
        type: 'ai',
        content: `I understand you're asking about "${input}". Here's a detailed response based on my knowledge:

This is a simulated AI response. In a real application, this would be generated by .

**Key points about your query:**
- First important point related to "${input}"
- Second detailed explanation with context
- Practical application or implementation suggestion
- Additional insights or recommendations
Would you like me to elaborate on any specific aspect?`,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        model: 'GPT-4',
        thinking: false,
      };
      setMessages((prev) => [...prev, aiResponse]);
      setIsThinking(false);
    }, 1500);
  };

  const handleCopy = (text) => {
    navigator.clipboard.writeText(text);
    // You could add a toast notification here
  };

  const handleFeedback = (messageId, type) => {
    console.log(`Feedback ${type} for message ${messageId}`);
    // You could add a toast notification here
  };

  const handleQuickPrompt = (prompt) => {
    setInput(prompt);
  };

  return (
    <div className="flex h-screen w-full overflow-hidden bg-gradient-to-br from-gray-50 to-gray-100">
      {/* Main Chat Area */}
      <div className="flex flex-1 flex-col">
        {/* Header */}

        {/* Messages Container */}
        <div className="flex-1 overflow-y-auto">
          {messages.length === 0 ? (
            <div className="flex h-full flex-col items-center justify-center p-6">
              <div className="mb-6 flex h-20 w-20 items-center justify-center rounded-full bg-gradient-to-br from-blue-100 to-purple-100">
                <Bot className="h-10 w-10 text-blue-600" />
              </div>
              <h2 className="mb-2 text-2xl font-bold text-gray-800">How can I help you today?</h2>
              <p className="mb-8 max-w-md text-center text-gray-600">
                Ask me anything! I can help with coding, writing, analysis, and much more.
              </p>

              <div className="mb-8 grid w-full max-w-2xl grid-cols-2 gap-3">
                {suggestedPrompts.map((prompt, idx) => (
                  <button
                    key={idx}
                    onClick={() => handleQuickPrompt(prompt)}
                    className="rounded-xl border border-gray-200 bg-white p-4 text-left transition-all hover:border-blue-300 hover:bg-blue-50/50 hover:shadow-md"
                  >
                    <div className="mb-1 flex items-center gap-2">
                      <Sparkles className="h-4 w-4 text-blue-500" />
                      <span className="text-sm font-medium text-gray-700">Quick prompt</span>
                    </div>
                    <p className="text-gray-800">{prompt}</p>
                  </button>
                ))}
              </div>
            </div>
          ) : (
            <div className="mx-auto max-w-4xl">
              {/* Left-aligned AI Messages and Right-aligned User Messages */}
              {messages.map((message) =>
                message.type === 'ai' ? (
                  <AIMessage
                    key={message.id}
                    message={message}
                    onCopy={handleCopy}
                    onFeedback={handleFeedback}
                  />
                ) : (
                  <UserMessage key={message.id} message={message} />
                )
              )}

              {isThinking && (
                <div className="flex gap-1">
                  <div
                    className="h-2 w-2 animate-bounce rounded-full bg-gray-300"
                    style={{ animationDelay: '0ms' }}
                  />
                  <div
                    className="h-2 w-2 animate-bounce rounded-full bg-gray-300"
                    style={{ animationDelay: '150ms' }}
                  />
                  <div
                    className="h-2 w-2 animate-bounce rounded-full bg-gray-300"
                    style={{ animationDelay: '300ms' }}
                  />
                </div>
              )}
              <div ref={messagesEndRef} />
            </div>
          )}
        </div>

        {/* Input Area */}
        <div className="sticky bottom-0 bg-gradient-to-t from-white via-white to-transparent px-6 pt-6 pb-8">
          <div className="mx-auto max-w-4xl">
            <form onSubmit={handleSend} className="relative">
              <div className="relative">
                <textarea
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  placeholder={`Ask anything...`}
                  className="w-full resize-none rounded-2xl border border-gray-200 bg-white px-6 py-4 pr-24 shadow-sm focus:border-transparent focus:ring-2 focus:ring-blue-500 focus:outline-none"
                  rows="3"
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' && !e.shiftKey) {
                      e.preventDefault();
                      handleSend(e);
                    }
                  }}
                />

                <div className="absolute right-4 bottom-4 flex items-center gap-2">
                  <span className="text-xs text-gray-500">{input.length}/4000</span>
                  <button
                    type="submit"
                    disabled={!input.trim() || isThinking}
                    className={`flex items-center gap-2 rounded-lg px-4 py-2 transition-all ${
                      input.trim() && !isThinking
                        ? 'bg-gradient-to-r from-blue-500 to-purple-600 text-white hover:shadow-lg'
                        : 'bg-gray-100 text-gray-400'
                    }`}
                  >
                    {isThinking ? (
                      <>
                        <div className="h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent" />
                        <span>Thinking...</span>
                      </>
                    ) : (
                      <>
                        <Send className="h-4 w-4" />
                        <span>Send</span>
                      </>
                    )}
                  </button>
                </div>
              </div>

              <div className="mt-3 flex items-center justify-between px-2">
                <p className="text-xs text-gray-500">
                  AI can make mistakes. Consider checking important information.
                </p>
                <div className="flex items-center gap-4">
                  <button type="button" className="text-xs text-gray-500 hover:text-gray-700">
                    ↻ Regenerate
                  </button>
                  <button type="button" className="text-xs text-gray-500 hover:text-gray-700">
                    ⏎ Enter to send
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AIChatView;
