import React from 'react';
import CategoryPageLayout from '../../../../components/ui/CategoryPageLayout';

const products = [
  {
    icon: '\u{1F527}',
    image: 'https://loremflickr.com/300/300/tools?seed=1',
    name: 'Cordless Drill Driver 20V',
    store: 'ToolMaster',
    price: '$79.99',
    old: '$129.99',
    off: '-38%',
    rating: '4.8',
    reviews: '2.1k',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1FA9A}',
    image: 'https://loremflickr.com/300/300/tools?seed=2',
    name: 'Professional Tool Set 256pc',
    store: 'CraftPro',
    price: '$149.00',
    old: '$249.00',
    off: '-40%',
    rating: '4.9',
    reviews: '1.5k',
    badge: 'TOP',
    wishlist: true,
  },
  {
    icon: '\u{1FA93}',
    image: 'https://loremflickr.com/300/300/tools?seed=3',
    name: 'Circular Saw 7¼" 15A',
    store: 'PowerCut',
    price: '$89.99',
    old: '$149.99',
    off: '-40%',
    rating: '4.7',
    reviews: '876',
    badge: 'HOT',
    wishlist: false,
  },
  {
    icon: '\u{1F4CF}',
    image: 'https://loremflickr.com/300/300/tools?seed=4',
    name: 'Laser Level Self-Leveling',
    store: 'PrecisionPro',
    price: '$34.99',
    old: '$59.99',
    off: '-42%',
    rating: '4.6',
    reviews: '432',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1FA9B}',
    image: 'https://loremflickr.com/300/300/tools?seed=5',
    name: 'Screwdriver Bit Set 100pc',
    store: 'ToolMaster',
    price: '$19.99',
    old: '$34.99',
    off: '-43%',
    rating: '4.5',
    reviews: '567',
    badge: 'NEW',
    wishlist: false,
  },
  {
    icon: '\u{1F3A8}',
    image: 'https://loremflickr.com/300/300/tools?seed=6',
    name: 'Paint Sprayer HVLP 800W',
    store: 'PaintPro',
    price: '$69.99',
    old: '$119.99',
    off: '-42%',
    rating: '4.6',
    reviews: '234',
    badge: 'HOT',
    wishlist: false,
  },
  {
    icon: '\u{1F6E0}',
    image: 'https://loremflickr.com/300/300/tools?seed=7',
    name: 'Workbench Portable Folding',
    store: 'ShopSetup',
    price: '$99.99',
    old: '$169.99',
    off: '-41%',
    rating: '4.7',
    reviews: '345',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F50A}',
    image: 'https://loremflickr.com/300/300/tools?seed=8',
    name: 'Air Compressor Portable 6gal',
    store: 'AirForce',
    price: '$119.00',
    old: '$199.00',
    off: '-40%',
    rating: '4.5',
    reviews: '187',
    badge: 'NEW',
    wishlist: false,
  },
  {
    icon: '\u{1F9F0}',
    image: 'https://loremflickr.com/300/300/tools?seed=9',
    name: 'Home Repair Tool Kit 65pc',
    store: 'FixIt',
    price: '$39.99',
    old: '$64.99',
    off: '-38%',
    rating: '4.6',
    reviews: '654',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1FA9C}',
    image: 'https://loremflickr.com/300/300/tools?seed=10',
    name: 'Electric Sander Orbital',
    store: 'SmoothFinish',
    price: '$44.99',
    old: '$74.99',
    off: '-40%',
    rating: '4.4',
    reviews: '312',
    badge: 'HOT',
    wishlist: false,
  },
  {
    icon: '\u{1F4A1}',
    image: 'https://loremflickr.com/300/300/tools?seed=11',
    name: 'LED Work Light Rechargeable',
    store: 'BrightWork',
    price: '$24.99',
    old: '$39.99',
    off: '-38%',
    rating: '4.7',
    reviews: '456',
    badge: 'NEW',
    wishlist: false,
  },
  {
    icon: '\u{1F4CF}',
    image: 'https://loremflickr.com/300/300/tools?seed=12',
    name: 'Digital Measuring Tape 25ft',
    store: 'PrecisionPro',
    price: '$14.99',
    old: '$24.99',
    off: '-40%',
    rating: '4.5',
    reviews: '789',
    badge: 'SALE',
    wishlist: false,
  },
];

const ToolsDIYSection = () => (
  <CategoryPageLayout
    title="Tools & DIY"
    icon={'\u{1F527}'}
    description="Power tools, hand tools, hardware, and everything for your DIY projects."
    products={products}
  />
);

export default ToolsDIYSection;
