import React from 'react';
import CategoryPageLayout from '../../../../components/ui/CategoryPageLayout';

const products = [
  {
    icon: '\u{1F48A}',
    name: 'Multivitamin Complex 90ct',
    store: 'VitaWell',
    price: '$19.99',
    old: '$34.99',
    off: '-43%',
    rating: '4.7',
    reviews: '2.3k',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F9D8}',
    name: 'Yoga Block Set Cork 2-Pack',
    store: 'ZenFit',
    price: '$14.99',
    old: '$24.99',
    off: '-40%',
    rating: '4.6',
    reviews: '567',
    badge: 'NEW',
    wishlist: false,
  },
  {
    icon: '\u{1FA7A}',
    name: 'Digital Blood Pressure Monitor',
    store: 'MedTech',
    price: '$39.99',
    old: '$69.99',
    off: '-43%',
    rating: '4.8',
    reviews: '1.5k',
    badge: 'TOP',
    wishlist: true,
  },
  {
    icon: '\u{1F4AA}',
    name: 'Whey Protein Isolate 2lb',
    store: 'MuscleFuel',
    price: '$29.99',
    old: '$49.99',
    off: '-40%',
    rating: '4.7',
    reviews: '3.4k',
    badge: 'HOT',
    wishlist: false,
  },
  {
    icon: '\u{1F9C2}',
    name: 'Omega-3 Fish Oil 120 Softgels',
    store: 'PureHealth',
    price: '$16.99',
    old: '$29.99',
    off: '-43%',
    rating: '4.5',
    reviews: '876',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F33F}',
    name: 'Organic Turmeric Capsules',
    store: 'HerbLife',
    price: '$12.99',
    old: '$22.99',
    off: '-43%',
    rating: '4.6',
    reviews: '654',
    badge: 'NEW',
    wishlist: false,
  },
  {
    icon: '\u{2696}',
    name: 'Smart Body Scale WiFi',
    store: 'FitTrack',
    price: '$34.99',
    old: '$59.99',
    off: '-42%',
    rating: '4.7',
    reviews: '1.2k',
    badge: 'HOT',
    wishlist: false,
  },
  {
    icon: '\u{1F6CC}',
    name: 'Melatonin Sleep Gummies 60ct',
    store: 'DreamWell',
    price: '$11.99',
    old: '$19.99',
    off: '-40%',
    rating: '4.4',
    reviews: '432',
    badge: 'SALE',
    wishlist: false,
  },
  {
    icon: '\u{1F489}',
    name: 'Collagen Peptides Powder 300g',
    store: 'GlowHealth',
    price: '$24.99',
    old: '$44.99',
    off: '-44%',
    rating: '4.8',
    reviews: '1.8k',
    badge: 'TOP',
    wishlist: false,
  },
  {
    icon: '\u{1F9B7}',
    name: 'Electric Toothbrush Sonic Pro',
    store: 'OralCare',
    price: '$44.99',
    old: '$79.99',
    off: '-44%',
    rating: '4.7',
    reviews: '2.1k',
    badge: 'SALE',
    wishlist: true,
  },
  {
    icon: '\u{1F3CB}',
    name: 'Resistance Bands Set 5-Level',
    store: 'FlexFit',
    price: '$14.99',
    old: '$24.99',
    off: '-40%',
    rating: '4.6',
    reviews: '1.5k',
    badge: 'HOT',
    wishlist: false,
  },
  {
    icon: '\u{1F9EA}',
    name: 'Probiotic 50 Billion CFU',
    store: 'GutHealth',
    price: '$22.99',
    old: '$39.99',
    off: '-43%',
    rating: '4.5',
    reviews: '987',
    badge: 'NEW',
    wishlist: false,
  },
];

const HealthSection = () => (
  <CategoryPageLayout
    title="Health"
    icon={'\u{1F48A}'}
    description="Vitamins, supplements, fitness equipment, and personal wellness essentials."
    products={products}
  />
);

export default HealthSection;
